#!/bin/bash
#BSUB -J check_chipset_output
#BSUB -o check_chipset_output%J.out
#BSUB -e check_chipset_output%J.err
#BSUB -q hpcintro
#BSUB -W 2
#BSUB -R "rusage[mem=512MB]"
#BSUB -R "select[model == XeonE5_2650v4]"

gcc -march=native -Q --help=target|grep march